### ISSUE TITLE
[Bug] Flags are permanently removed from the autocompletion

### ISSUE THREAD

**Issue by cmprmsd** [brianstrauch/cobra-shell#3]
## Bug
When I have e.g. two flags like the following:
![image](https://user-images.githubusercontent.com/73472903/164947085-f82871ed-92cd-4fd3-8350-1954d19ff0eb.png)

I can use them one time. Afterwards they will be removed. This is expected and good.
![image](https://user-images.githubusercontent.com/73472903/164947121-ff5bb428-b166-4f79-95aa-05cb756aeecf.png)

However, when I now press `up` or rewrite the commands the used completion flags are gone.
![image](https://user-images.githubusercontent.com/73472903/164947072-d1184a78-fda2-49a2-90e1-1cbf08235f15.png)

## Fix
The flags should be re-enabled after each execution.

Edit: I saw you already tried to fix this issue in https://github.com/brianstrauch/cobra-shell/commit/db07c08a0692da8f1c0d8400fdce7fb81be5fd15. 
However, I'm on 0.2.4 so maybe the fix is not complete.

**Comment by brianstrauch** [comment]
Thanks for reporting! Fixed in [v0.2.5](https://github.com/brianstrauch/cobra-shell/tree/v0.2.5)

**Comment by cmprmsd** [comment]
Nice!

One minor glitch I noticed is when you use backspace after completing a word sometimes it still gets removed from the suggestions as in this case --gzip:
![image](https://user-images.githubusercontent.com/73472903/165631735-0b051f8d-4727-4399-8331-ad77146efc21.png)
